### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by patrickblattner** [pugong/mkdocs-mermaid-plugin#1]
Please add a Python version query to the file "plugin.py" for the "Return Value". Otherwise the following error will be displayed under Python 3.x, when starting the server:
"NameError: name 'unicode' is not defined"

The following variants have to be considered:
in python2.x:
return unicode(soup, 'utf-8')

in python3.x:
return str(soup.encode('utf-8'))

Thanks
Patrick

**Comment by noamsto** [comment]
I am using python 3.7 and ran into this problem when executing `mkdocs builds`.

@patrickblattner  i think you mean:
>  return str(soup.encode('utf-8'))

Should be:

`return str(soup.decode('utf-8'))`

At least that what solve the problem for me.

**Comment by bnounours** [comment]
Hello,

Same issue for me in python 3.6
```
  File "/usr/local/lib/python3.6/site-packages/mkdocs_mermaid_plugin-0.1.1-py3.6.egg/markdownmermaid/plugin.py", line 22, in on_post_page
NameError: name 'unicode' is not defined
```
