### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by itopaloglu83** [pugong/mkdocs-mermaid-plugin#10]
I did a fresh install and got the `unicode is not defined` error.

Mermaid2 solved this issue with the [this commit.](https://github.com/fralau/mkdocs-mermaid2-plugin/commit/bb41868a8b73ba9df853a0b0e0663faecbc15e69?branch=bb41868a8b73ba9df853a0b0e0663faecbc15e69&diff=unified) It's a compatibility issue with Python 3.

When `mkdocs build` is run the following output takes place.

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /.../site 
ERROR   -  Error building page 'index.md': name 'unicode' is not defined 
...
.../lib/python3.7/site-packages/markdownmermaid/plugin.py", line 22, in on_post_page
    return unicode(soup)
NameError: name 'unicode' is not defined
```

**Comment by maschmi1** [comment]
@itopaloglu83 I was getting the same thing. If you pull directly from the repository, it has the `unicode = str` fix

**Comment by itopaloglu83** [comment]
Well, we need to wait for the `pip` release then.
